# Generated by Django 5.1.6 on 2025-02-16 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift_compass", "0003_alter_choice_owner_alter_content_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectedChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="Respondent",
        ),
        migrations.AddField(
            model_name="answer",
            name="respondent_name",
            field=models.CharField(default="anony", max_length=100),
        ),
        migrations.AlterField(
            model_name="answer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="gift_compass.page",
            ),
        ),
        migrations.AddField(
            model_name="selectedchoice",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_choice",
                to="gift_compass.answer",
            ),
        ),
    ]
